import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "webpt21b",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/images/Icono.png" type="image/png" />
      </head>
      {/* Aplica Inter al HTML completo */}
      <body className={inter.className}> 
        <Navbar />

        {/* Aquí puedes aplicar la fuente Roboto a una sección específica */}
        <div className={roboto.className}>
          {children} {/* Aplica Roboto a los children */}
        </div>

        <Footer />
      </body>
    </html>
  );
}

